### ISSUE TITLE
Changing value but UI not updating.

### ISSUE THREAD

**Issue by Robin-AF** [tianzhuqiao/form#3]
Hi,

Thanks for this wonderful library, as soon as I have more time I will contribute more to it.
I'm curently trying to change data and see it reflect it's changes in the form.

For example

```
+FormItemLabel()
     .tag("Test")
    .title("Test")
    .subTitle("Test")
    .onItemClicked { item, viewHolder ->
       item.subTitle = "Test 2"
    }
 ```
 
 Based on the above code, I would expect the subtext to change to "Test 2" when I press the item.  Unfortunatly nothing happens, probably some kind of binding I need to activate?
 
 (P.S I'm trying to do this in a custom FormITem but showing it in the FormItemLabel for testing purposes.)

Any help is welcome!

**Comment by tianzhuqiao** [comment]
How about calling `adapter?.updateItem(item) ` after changing the item?
```
+FormItemLabel()
     .tag("Test")
    .title("Test")
    .subTitle("Test")
    .onItemClicked { item, viewHolder ->
       item.subTitle = "Test 2"
       adapter?.updateItem(item) 
    }

```

**Comment by Robin-AF** [comment]
Works perfectly thanks!
